OpenNSL API Guide and Reference Manual: include/sal/driver.h File Reference
include/sal/driver.h File Reference
Data Structures
struct opennsl_config_s
Typedefs
typedef struct opennsl_config_s opennsl_init_t
Functions
unsigned int opennsl_driver_boot_flags_get (void)
To get platform boot flags.
int opennsl_driver_init (opennsl_init_t *init)
Function to initialize the switch.
int opennsl_driver_process_command (char *commandBuf)
Process diagnostic shell command.
int opennsl_driver_shell ()
Bringup diagnostic shell prompt and process the input commands.
char * readline (const char *prompt)
Typedef Documentation
typedef struct opennsl_config_s opennsl_init_t
Function Documentation
unsigned int opennsl_driver_boot_flags_get (void)
To get platform boot flags.
Returns:
unsigned int Boot flags
Referenced by main().
int opennsl_driver_init (opennsl_init_t * init)
Function to initialize the switch.
Parameters:
init [IN] pointer to structure that contains path to platform customization config file, boot flags.
Returns:
OPENNSL_E_XXX OpenNSL API return code
Referenced by main().
int opennsl_driver_process_command (char * commandBuf)
Process diagnostic shell command.
Parameters:
commandBuf [IN] pointer to hold the diagnostic shell command
Returns:
OPENNSL_E_XXX OpenNSL API return code
int opennsl_driver_shell ()
Bringup diagnostic shell prompt and process the input commands.
Returns:
OPENNSL_E_XXX OpenNSL API return code
Referenced by main().
char* readline (const char * prompt)